---
count: 6
default:
  restart: 0
  wait: 1
editor:
  files:
    eg:
      - bin/npmdoc
      - bin/npm-updater
    base:
      - lib/App/NpmUpdater.pm
    version:
      - lib/App/Npm/Version.pm
      - lib/App/Npm/Version/Range.pm
name: npm-updater
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: base
  3:
    edit: version
