=begin html

<a href="https://travis-ci.org/ivanwills/App-NpmUpdater"><img src="https://travis-ci.org/ivanwills/App-NpmUpdater.png" alt="App-NpmUpdater"></a>
<a href="https://coveralls.io/r/ivanwills/App-NpmUpdater?branch=master"><img src="https://coveralls.io/repos/ivanwills/App-NpmUpdater/badge.svg?branch=master" alt="Coverage Status" /></a>

=head1 App-NpmUpdater

The App-NpmUpdater package provides tools to work with npm packages
to help keep them up to date.

=head1 INSTALLATION

To install this module, run the following commands:

    perl Build.PL
    ./Build
    ./Build test
    ./Build install

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc App::NpmUpdater

You can also look for information at:

    RT, CPAN's request tracker
        http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-NpmUpdater

    AnnoCPAN, Annotated CPAN documentation
        http://annocpan.org/dist/App-NpmUpdater

    CPAN Ratings
        http://cpanratings.perl.org/d/App-NpmUpdater

    Search CPAN
        http://search.cpan.org/dist/App-NpmUpdater/

    Source Code
        git://github.com/ivanwills/App-NpmUpdater.git

=head1 COPYRIGHT AND LICENCE

=head1 Copyright (C) 2016 Ivan Wills

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

=cut
